// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go
//
// Generated by this command:
//
//	mockgen -source consumer.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	consumer "github.com/n1jke/linktracker/internal/bot/infrastructure/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockInboxRepository is a mock of InboxRepository interface.
type MockInboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInboxRepositoryMockRecorder
	isgomock struct{}
}

// MockInboxRepositoryMockRecorder is the mock recorder for MockInboxRepository.
type MockInboxRepositoryMockRecorder struct {
	mock *MockInboxRepository
}

// NewMockInboxRepository creates a new mock instance.
func NewMockInboxRepository(ctrl *gomock.Controller) *MockInboxRepository {
	mock := &MockInboxRepository{ctrl: ctrl}
	mock.recorder = &MockInboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxRepository) EXPECT() *MockInboxRepositoryMockRecorder {
	return m.recorder
}

// AddRecord mocks base method.
func (m *MockInboxRepository) AddRecord(ctx context.Context, rec *consumer.InboxRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockInboxRepositoryMockRecorder) AddRecord(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockInboxRepository)(nil).AddRecord), ctx, rec)
}
