// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source interfaces.go -destination=mocks/mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bot "github.com/go-telegram/bot"
	models "github.com/go-telegram/bot/models"
	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyRepository is a mock of IdempotencyRepository interface.
type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockIdempotencyRepositoryMockRecorder is the mock recorder for MockIdempotencyRepository.
type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

// NewMockIdempotencyRepository creates a new mock instance.
func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// IsDuplicate mocks base method.
func (m *MockIdempotencyRepository) IsDuplicate(msg *kafka.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDuplicate", msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDuplicate indicates an expected call of IsDuplicate.
func (mr *MockIdempotencyRepositoryMockRecorder) IsDuplicate(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDuplicate", reflect.TypeOf((*MockIdempotencyRepository)(nil).IsDuplicate), msg)
}

// MockBotNotifier is a mock of BotNotifier interface.
type MockBotNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockBotNotifierMockRecorder
	isgomock struct{}
}

// MockBotNotifierMockRecorder is the mock recorder for MockBotNotifier.
type MockBotNotifierMockRecorder struct {
	mock *MockBotNotifier
}

// NewMockBotNotifier creates a new mock instance.
func NewMockBotNotifier(ctrl *gomock.Controller) *MockBotNotifier {
	mock := &MockBotNotifier{ctrl: ctrl}
	mock.recorder = &MockBotNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotNotifier) EXPECT() *MockBotNotifierMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockBotNotifier) SendMessage(ctx context.Context, params *bot.SendMessageParams) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, params)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockBotNotifierMockRecorder) SendMessage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockBotNotifier)(nil).SendMessage), ctx, params)
}
