// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: link_tracker.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrapperService_RegisterChat_FullMethodName = "/linktracker.ScrapperService/RegisterChat"
	ScrapperService_TrackLink_FullMethodName    = "/linktracker.ScrapperService/TrackLink"
	ScrapperService_UntrackLink_FullMethodName  = "/linktracker.ScrapperService/UntrackLink"
	ScrapperService_ListLinks_FullMethodName    = "/linktracker.ScrapperService/ListLinks"
	ScrapperService_AddTags_FullMethodName      = "/linktracker.ScrapperService/AddTags"
	ScrapperService_ClearTags_FullMethodName    = "/linktracker.ScrapperService/ClearTags"
)

// ScrapperServiceClient is the client API for ScrapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperServiceClient interface {
	RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TrackLink(ctx context.Context, in *TrackLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	UntrackLink(ctx context.Context, in *UntrackLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	AddTags(ctx context.Context, in *AddTagsRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	ClearTags(ctx context.Context, in *ClearTagsRequest, opts ...grpc.CallOption) (*LinkResponse, error)
}

type scrapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperServiceClient(cc grpc.ClientConnInterface) ScrapperServiceClient {
	return &scrapperServiceClient{cc}
}

func (c *scrapperServiceClient) RegisterChat(ctx context.Context, in *RegisterChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ScrapperService_RegisterChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) TrackLink(ctx context.Context, in *TrackLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperService_TrackLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) UntrackLink(ctx context.Context, in *UntrackLinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperService_UntrackLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, ScrapperService_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) AddTags(ctx context.Context, in *AddTagsRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperService_AddTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) ClearTags(ctx context.Context, in *ClearTagsRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, ScrapperService_ClearTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapperServiceServer is the server API for ScrapperService service.
// All implementations must embed UnimplementedScrapperServiceServer
// for forward compatibility.
type ScrapperServiceServer interface {
	RegisterChat(context.Context, *RegisterChatRequest) (*emptypb.Empty, error)
	TrackLink(context.Context, *TrackLinkRequest) (*LinkResponse, error)
	UntrackLink(context.Context, *UntrackLinkRequest) (*LinkResponse, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	AddTags(context.Context, *AddTagsRequest) (*LinkResponse, error)
	ClearTags(context.Context, *ClearTagsRequest) (*LinkResponse, error)
	mustEmbedUnimplementedScrapperServiceServer()
}

// UnimplementedScrapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrapperServiceServer struct{}

func (UnimplementedScrapperServiceServer) RegisterChat(context.Context, *RegisterChatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterChat not implemented")
}
func (UnimplementedScrapperServiceServer) TrackLink(context.Context, *TrackLinkRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackLink not implemented")
}
func (UnimplementedScrapperServiceServer) UntrackLink(context.Context, *UntrackLinkRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UntrackLink not implemented")
}
func (UnimplementedScrapperServiceServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedScrapperServiceServer) AddTags(context.Context, *AddTagsRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTags not implemented")
}
func (UnimplementedScrapperServiceServer) ClearTags(context.Context, *ClearTagsRequest) (*LinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTags not implemented")
}
func (UnimplementedScrapperServiceServer) mustEmbedUnimplementedScrapperServiceServer() {}
func (UnimplementedScrapperServiceServer) testEmbeddedByValue()                         {}

// UnsafeScrapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperServiceServer will
// result in compilation errors.
type UnsafeScrapperServiceServer interface {
	mustEmbedUnimplementedScrapperServiceServer()
}

func RegisterScrapperServiceServer(s grpc.ServiceRegistrar, srv ScrapperServiceServer) {
	// If the following call panics, it indicates UnimplementedScrapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrapperService_ServiceDesc, srv)
}

func _ScrapperService_RegisterChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_RegisterChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, req.(*RegisterChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_TrackLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).TrackLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_TrackLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).TrackLink(ctx, req.(*TrackLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_UntrackLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntrackLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).UntrackLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_UntrackLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).UntrackLink(ctx, req.(*UntrackLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_AddTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).AddTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_AddTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).AddTags(ctx, req.(*AddTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_ClearTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).ClearTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_ClearTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).ClearTags(ctx, req.(*ClearTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapperService_ServiceDesc is the grpc.ServiceDesc for ScrapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linktracker.ScrapperService",
	HandlerType: (*ScrapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChat",
			Handler:    _ScrapperService_RegisterChat_Handler,
		},
		{
			MethodName: "TrackLink",
			Handler:    _ScrapperService_TrackLink_Handler,
		},
		{
			MethodName: "UntrackLink",
			Handler:    _ScrapperService_UntrackLink_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _ScrapperService_ListLinks_Handler,
		},
		{
			MethodName: "AddTags",
			Handler:    _ScrapperService_AddTags_Handler,
		},
		{
			MethodName: "ClearTags",
			Handler:    _ScrapperService_ClearTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link_tracker.proto",
}

const (
	BotService_PostUpdate_FullMethodName = "/linktracker.BotService/PostUpdate"
)

// BotServiceClient is the client API for BotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotServiceClient interface {
	PostUpdate(ctx context.Context, in *LinkUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type botServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotServiceClient(cc grpc.ClientConnInterface) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) PostUpdate(ctx context.Context, in *LinkUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BotService_PostUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServiceServer is the server API for BotService service.
// All implementations must embed UnimplementedBotServiceServer
// for forward compatibility.
type BotServiceServer interface {
	PostUpdate(context.Context, *LinkUpdate) (*emptypb.Empty, error)
	mustEmbedUnimplementedBotServiceServer()
}

// UnimplementedBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotServiceServer struct{}

func (UnimplementedBotServiceServer) PostUpdate(context.Context, *LinkUpdate) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PostUpdate not implemented")
}
func (UnimplementedBotServiceServer) mustEmbedUnimplementedBotServiceServer() {}
func (UnimplementedBotServiceServer) testEmbeddedByValue()                    {}

// UnsafeBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServiceServer will
// result in compilation errors.
type UnsafeBotServiceServer interface {
	mustEmbedUnimplementedBotServiceServer()
}

func RegisterBotServiceServer(s grpc.ServiceRegistrar, srv BotServiceServer) {
	// If the following call panics, it indicates UnimplementedBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotService_ServiceDesc, srv)
}

func _BotService_PostUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).PostUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_PostUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).PostUpdate(ctx, req.(*LinkUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// BotService_ServiceDesc is the grpc.ServiceDesc for BotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linktracker.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostUpdate",
			Handler:    _BotService_PostUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link_tracker.proto",
}
