// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: link_tracker.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatRequest) Reset() {
	*x = RegisterChatRequest{}
	mi := &file_link_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatRequest) ProtoMessage() {}

func (x *RegisterChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatRequest.ProtoReflect.Descriptor instead.
func (*RegisterChatRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type TrackLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackLinkRequest) Reset() {
	*x = TrackLinkRequest{}
	mi := &file_link_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLinkRequest) ProtoMessage() {}

func (x *TrackLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLinkRequest.ProtoReflect.Descriptor instead.
func (*TrackLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *TrackLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TrackLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TrackLinkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UntrackLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntrackLinkRequest) Reset() {
	*x = UntrackLinkRequest{}
	mi := &file_link_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntrackLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntrackLinkRequest) ProtoMessage() {}

func (x *UntrackLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntrackLinkRequest.ProtoReflect.Descriptor instead.
func (*UntrackLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *UntrackLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UntrackLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_link_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *ListLinksRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type AddTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagsRequest) Reset() {
	*x = AddTagsRequest{}
	mi := &file_link_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagsRequest) ProtoMessage() {}

func (x *AddTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagsRequest.ProtoReflect.Descriptor instead.
func (*AddTagsRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *AddTagsRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *AddTagsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ClearTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTagsRequest) Reset() {
	*x = ClearTagsRequest{}
	mi := &file_link_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTagsRequest) ProtoMessage() {}

func (x *ClearTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTagsRequest.ProtoReflect.Descriptor instead.
func (*ClearTagsRequest) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *ClearTagsRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ClearTagsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_link_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *LinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkResponse        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_link_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *ListLinksResponse) GetLinks() []*LinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LinkUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ChatIds       []int64                `protobuf:"varint,4,rep,packed,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUpdate) Reset() {
	*x = LinkUpdate{}
	mi := &file_link_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpdate) ProtoMessage() {}

func (x *LinkUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_link_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpdate.ProtoReflect.Descriptor instead.
func (*LinkUpdate) Descriptor() ([]byte, []int) {
	return file_link_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *LinkUpdate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LinkUpdate) GetChatIds() []int64 {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

func (x *LinkUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_link_tracker_proto protoreflect.FileDescriptor

const file_link_tracker_proto_rawDesc = "" +
	"\n" +
	"\x12link_tracker.proto\x12\vlinktracker\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x13RegisterChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"Q\n" +
	"\x10TrackLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"?\n" +
	"\x12UntrackLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"+\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"O\n" +
	"\x0eAddTagsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"=\n" +
	"\x10ClearTagsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"D\n" +
	"\fLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"X\n" +
	"\x11ListLinksResponse\x12/\n" +
	"\x05links\x18\x01 \x03(\v2\x19.linktracker.LinkResponseR\x05links\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xa6\x01\n" +
	"\n" +
	"LinkUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bchat_ids\x18\x04 \x03(\x03R\achatIds\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xc3\x03\n" +
	"\x0fScrapperService\x12H\n" +
	"\fRegisterChat\x12 .linktracker.RegisterChatRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\tTrackLink\x12\x1d.linktracker.TrackLinkRequest\x1a\x19.linktracker.LinkResponse\x12I\n" +
	"\vUntrackLink\x12\x1f.linktracker.UntrackLinkRequest\x1a\x19.linktracker.LinkResponse\x12J\n" +
	"\tListLinks\x12\x1d.linktracker.ListLinksRequest\x1a\x1e.linktracker.ListLinksResponse\x12A\n" +
	"\aAddTags\x12\x1b.linktracker.AddTagsRequest\x1a\x19.linktracker.LinkResponse\x12E\n" +
	"\tClearTags\x12\x1d.linktracker.ClearTagsRequest\x1a\x19.linktracker.LinkResponse2K\n" +
	"\n" +
	"BotService\x12=\n" +
	"\n" +
	"PostUpdate\x12\x17.linktracker.LinkUpdate\x1a\x16.google.protobuf.EmptyBvZtgithub.com/n1jke/linktracker/internal/infrastructure/transport/grpc;grpcb\x06proto3"

var (
	file_link_tracker_proto_rawDescOnce sync.Once
	file_link_tracker_proto_rawDescData []byte
)

func file_link_tracker_proto_rawDescGZIP() []byte {
	file_link_tracker_proto_rawDescOnce.Do(func() {
		file_link_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_tracker_proto_rawDesc), len(file_link_tracker_proto_rawDesc)))
	})
	return file_link_tracker_proto_rawDescData
}

var (
	file_link_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
	file_link_tracker_proto_goTypes  = []any{
		(*RegisterChatRequest)(nil),   // 0: linktracker.RegisterChatRequest
		(*TrackLinkRequest)(nil),      // 1: linktracker.TrackLinkRequest
		(*UntrackLinkRequest)(nil),    // 2: linktracker.UntrackLinkRequest
		(*ListLinksRequest)(nil),      // 3: linktracker.ListLinksRequest
		(*AddTagsRequest)(nil),        // 4: linktracker.AddTagsRequest
		(*ClearTagsRequest)(nil),      // 5: linktracker.ClearTagsRequest
		(*LinkResponse)(nil),          // 6: linktracker.LinkResponse
		(*ListLinksResponse)(nil),     // 7: linktracker.ListLinksResponse
		(*LinkUpdate)(nil),            // 8: linktracker.LinkUpdate
		(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
		(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
	}
)
var file_link_tracker_proto_depIdxs = []int32{
	6,  // 0: linktracker.ListLinksResponse.links:type_name -> linktracker.LinkResponse
	9,  // 1: linktracker.LinkUpdate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: linktracker.ScrapperService.RegisterChat:input_type -> linktracker.RegisterChatRequest
	1,  // 3: linktracker.ScrapperService.TrackLink:input_type -> linktracker.TrackLinkRequest
	2,  // 4: linktracker.ScrapperService.UntrackLink:input_type -> linktracker.UntrackLinkRequest
	3,  // 5: linktracker.ScrapperService.ListLinks:input_type -> linktracker.ListLinksRequest
	4,  // 6: linktracker.ScrapperService.AddTags:input_type -> linktracker.AddTagsRequest
	5,  // 7: linktracker.ScrapperService.ClearTags:input_type -> linktracker.ClearTagsRequest
	8,  // 8: linktracker.BotService.PostUpdate:input_type -> linktracker.LinkUpdate
	10, // 9: linktracker.ScrapperService.RegisterChat:output_type -> google.protobuf.Empty
	6,  // 10: linktracker.ScrapperService.TrackLink:output_type -> linktracker.LinkResponse
	6,  // 11: linktracker.ScrapperService.UntrackLink:output_type -> linktracker.LinkResponse
	7,  // 12: linktracker.ScrapperService.ListLinks:output_type -> linktracker.ListLinksResponse
	6,  // 13: linktracker.ScrapperService.AddTags:output_type -> linktracker.LinkResponse
	6,  // 14: linktracker.ScrapperService.ClearTags:output_type -> linktracker.LinkResponse
	10, // 15: linktracker.BotService.PostUpdate:output_type -> google.protobuf.Empty
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_link_tracker_proto_init() }
func file_link_tracker_proto_init() {
	if File_link_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_tracker_proto_rawDesc), len(file_link_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_link_tracker_proto_goTypes,
		DependencyIndexes: file_link_tracker_proto_depIdxs,
		MessageInfos:      file_link_tracker_proto_msgTypes,
	}.Build()
	File_link_tracker_proto = out.File
	file_link_tracker_proto_goTypes = nil
	file_link_tracker_proto_depIdxs = nil
}
