port 26379
bind 0.0.0.0

sentinel announce-hostnames yes
sentinel resolve-hostnames yes

sentinel monitor master valkey-1 6379 2

sentinel auth-user master <username>
sentinel auth-pass master <password>

sentinel down-after-milliseconds master 5000
sentinel parallel-syncs master 1
sentinel failover-timeout master 180000
