bind 0.0.0.0
port 6379
protected-mode yes
logfile ""
dir ./
dbfilename valkey-data.rdb
aclfile /etc/valkey/users.acl

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
stop-writes-on-bgsave-error yes
rdbcompression yes

# replicas
replica-read-only yes
replica-serve-stale-data no
repl-timeout 60

# limits
maxclients 30000
tcp-backlog 65535
databases 16
lua-time-limit 5000

# memory
hash-max-ziplist-entries 2048
hash-max-ziplist-value 256
list-max-ziplist-entries 2048
list-max-ziplist-value 256
set-max-intset-entries 2048
zset-max-ziplist-entries 512
zset-max-ziplist-value 256
activerehashing yes

# buffers
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 512mb 512mb 0
client-output-buffer-limit pubsub 32mb 8mb 60

# slow-logs
slowlog-log-slower-than 10000
slowlog-max-len 1024
