// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	application "github.com/n1jke/linktracker_eng/internal/scrapper/application"
	domain "github.com/n1jke/linktracker_eng/internal/scrapper/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTransactor) WithTransaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTransactorMockRecorder) WithTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTransactor)(nil).WithTransaction), arg0, arg1)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockUserRepository) AddClient(ctx context.Context, client *domain.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClient indicates an expected call of AddClient.
func (mr *MockUserRepositoryMockRecorder) AddClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockUserRepository)(nil).AddClient), ctx, client)
}

// GetClientByID mocks base method.
func (m *MockUserRepository) GetClientByID(ctx context.Context, clientID int64) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByID", ctx, clientID)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByID indicates an expected call of GetClientByID.
func (mr *MockUserRepositoryMockRecorder) GetClientByID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByID", reflect.TypeOf((*MockUserRepository)(nil).GetClientByID), ctx, clientID)
}

// RemoveClient mocks base method.
func (m *MockUserRepository) RemoveClient(ctx context.Context, clientID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClient", ctx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClient indicates an expected call of RemoveClient.
func (mr *MockUserRepositoryMockRecorder) RemoveClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClient", reflect.TypeOf((*MockUserRepository)(nil).RemoveClient), ctx, clientID)
}

// MockLinksRepository is a mock of LinksRepository interface.
type MockLinksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinksRepositoryMockRecorder
	isgomock struct{}
}

// MockLinksRepositoryMockRecorder is the mock recorder for MockLinksRepository.
type MockLinksRepositoryMockRecorder struct {
	mock *MockLinksRepository
}

// NewMockLinksRepository creates a new mock instance.
func NewMockLinksRepository(ctrl *gomock.Controller) *MockLinksRepository {
	mock := &MockLinksRepository{ctrl: ctrl}
	mock.recorder = &MockLinksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksRepository) EXPECT() *MockLinksRepositoryMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockLinksRepository) AddLink(ctx context.Context, link *domain.TrackedLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinksRepositoryMockRecorder) AddLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinksRepository)(nil).AddLink), ctx, link)
}

// GetLinkByID mocks base method.
func (m *MockLinksRepository) GetLinkByID(ctx context.Context, linkID uuid.UUID) (*domain.TrackedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkByID", ctx, linkID)
	ret0, _ := ret[0].(*domain.TrackedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkByID indicates an expected call of GetLinkByID.
func (mr *MockLinksRepositoryMockRecorder) GetLinkByID(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkByID", reflect.TypeOf((*MockLinksRepository)(nil).GetLinkByID), ctx, linkID)
}

// GetLinkByName mocks base method.
func (m *MockLinksRepository) GetLinkByName(ctx context.Context, name string) (*domain.TrackedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkByName", ctx, name)
	ret0, _ := ret[0].(*domain.TrackedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkByName indicates an expected call of GetLinkByName.
func (mr *MockLinksRepositoryMockRecorder) GetLinkByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkByName", reflect.TypeOf((*MockLinksRepository)(nil).GetLinkByName), ctx, name)
}

// GetLinksBatch mocks base method.
func (m *MockLinksRepository) GetLinksBatch(ctx context.Context, limit int, pointer *time.Time) ([]*domain.TrackedLink, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinksBatch", ctx, limit, pointer)
	ret0, _ := ret[0].([]*domain.TrackedLink)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLinksBatch indicates an expected call of GetLinksBatch.
func (mr *MockLinksRepositoryMockRecorder) GetLinksBatch(ctx, limit, pointer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinksBatch", reflect.TypeOf((*MockLinksRepository)(nil).GetLinksBatch), ctx, limit, pointer)
}

// RemoveLink mocks base method.
func (m *MockLinksRepository) RemoveLink(ctx context.Context, linkID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockLinksRepositoryMockRecorder) RemoveLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockLinksRepository)(nil).RemoveLink), ctx, linkID)
}

// MockLinksCache is a mock of LinksCache interface.
type MockLinksCache struct {
	ctrl     *gomock.Controller
	recorder *MockLinksCacheMockRecorder
	isgomock struct{}
}

// MockLinksCacheMockRecorder is the mock recorder for MockLinksCache.
type MockLinksCacheMockRecorder struct {
	mock *MockLinksCache
}

// NewMockLinksCache creates a new mock instance.
func NewMockLinksCache(ctrl *gomock.Controller) *MockLinksCache {
	mock := &MockLinksCache{ctrl: ctrl}
	mock.recorder = &MockLinksCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksCache) EXPECT() *MockLinksCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLinksCache) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinksCacheMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinksCache)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockLinksCache) Get(ctx context.Context, key string) ([]*domain.LinkSubscription, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]*domain.LinkSubscription)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockLinksCacheMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinksCache)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockLinksCache) Set(ctx context.Context, key string, links []*domain.LinkSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockLinksCacheMockRecorder) Set(ctx, key, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockLinksCache)(nil).Set), ctx, key, links)
}

// MockSubscriptionsRepository is a mock of SubscriptionsRepository interface.
type MockSubscriptionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionsRepositoryMockRecorder is the mock recorder for MockSubscriptionsRepository.
type MockSubscriptionsRepositoryMockRecorder struct {
	mock *MockSubscriptionsRepository
}

// NewMockSubscriptionsRepository creates a new mock instance.
func NewMockSubscriptionsRepository(ctrl *gomock.Controller) *MockSubscriptionsRepository {
	mock := &MockSubscriptionsRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsRepository) EXPECT() *MockSubscriptionsRepositoryMockRecorder {
	return m.recorder
}

// AddSubscription mocks base method.
func (m *MockSubscriptionsRepository) AddSubscription(ctx context.Context, subscription *domain.LinkSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockSubscriptionsRepositoryMockRecorder) AddSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscription", reflect.TypeOf((*MockSubscriptionsRepository)(nil).AddSubscription), ctx, subscription)
}

// AddTags mocks base method.
func (m *MockSubscriptionsRepository) AddTags(ctx context.Context, userID int64, resourceID uuid.UUID, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTags", ctx, userID, resourceID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTags indicates an expected call of AddTags.
func (mr *MockSubscriptionsRepositoryMockRecorder) AddTags(ctx, userID, resourceID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTags", reflect.TypeOf((*MockSubscriptionsRepository)(nil).AddTags), ctx, userID, resourceID, tags)
}

// ClearTags mocks base method.
func (m *MockSubscriptionsRepository) ClearTags(ctx context.Context, userID int64, resourceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTags", ctx, userID, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTags indicates an expected call of ClearTags.
func (mr *MockSubscriptionsRepositoryMockRecorder) ClearTags(ctx, userID, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTags", reflect.TypeOf((*MockSubscriptionsRepository)(nil).ClearTags), ctx, userID, resourceID)
}

// GetSubscriptionsByResourceID mocks base method.
func (m *MockSubscriptionsRepository) GetSubscriptionsByResourceID(ctx context.Context, resourceID uuid.UUID) ([]*domain.LinkSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsByResourceID", ctx, resourceID)
	ret0, _ := ret[0].([]*domain.LinkSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsByResourceID indicates an expected call of GetSubscriptionsByResourceID.
func (mr *MockSubscriptionsRepositoryMockRecorder) GetSubscriptionsByResourceID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsByResourceID", reflect.TypeOf((*MockSubscriptionsRepository)(nil).GetSubscriptionsByResourceID), ctx, resourceID)
}

// GetSubscriptionsByUserID mocks base method.
func (m *MockSubscriptionsRepository) GetSubscriptionsByUserID(ctx context.Context, userID int64) ([]*domain.LinkSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.LinkSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsByUserID indicates an expected call of GetSubscriptionsByUserID.
func (mr *MockSubscriptionsRepositoryMockRecorder) GetSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsByUserID", reflect.TypeOf((*MockSubscriptionsRepository)(nil).GetSubscriptionsByUserID), ctx, userID)
}

// RemoveSubscription mocks base method.
func (m *MockSubscriptionsRepository) RemoveSubscription(ctx context.Context, subscription *domain.LinkSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubscription indicates an expected call of RemoveSubscription.
func (mr *MockSubscriptionsRepositoryMockRecorder) RemoveSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscription", reflect.TypeOf((*MockSubscriptionsRepository)(nil).RemoveSubscription), ctx, subscription)
}

// RemoveSubscriptionsByUserID mocks base method.
func (m *MockSubscriptionsRepository) RemoveSubscriptionsByUserID(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubscriptionsByUserID indicates an expected call of RemoveSubscriptionsByUserID.
func (mr *MockSubscriptionsRepositoryMockRecorder) RemoveSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscriptionsByUserID", reflect.TypeOf((*MockSubscriptionsRepository)(nil).RemoveSubscriptionsByUserID), ctx, userID)
}

// UpdateSubscriptionLastUpdate mocks base method.
func (m *MockSubscriptionsRepository) UpdateSubscriptionLastUpdate(ctx context.Context, userID int64, resourceID uuid.UUID, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionLastUpdate", ctx, userID, resourceID, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionLastUpdate indicates an expected call of UpdateSubscriptionLastUpdate.
func (mr *MockSubscriptionsRepositoryMockRecorder) UpdateSubscriptionLastUpdate(ctx, userID, resourceID, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionLastUpdate", reflect.TypeOf((*MockSubscriptionsRepository)(nil).UpdateSubscriptionLastUpdate), ctx, userID, resourceID, updatedAt)
}

// MockSourceCrawler is a mock of SourceCrawler interface.
type MockSourceCrawler struct {
	ctrl     *gomock.Controller
	recorder *MockSourceCrawlerMockRecorder
	isgomock struct{}
}

// MockSourceCrawlerMockRecorder is the mock recorder for MockSourceCrawler.
type MockSourceCrawlerMockRecorder struct {
	mock *MockSourceCrawler
}

// NewMockSourceCrawler creates a new mock instance.
func NewMockSourceCrawler(ctrl *gomock.Controller) *MockSourceCrawler {
	mock := &MockSourceCrawler{ctrl: ctrl}
	mock.recorder = &MockSourceCrawlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceCrawler) EXPECT() *MockSourceCrawlerMockRecorder {
	return m.recorder
}

// SearchResource mocks base method.
func (m *MockSourceCrawler) SearchResource(ctx context.Context, link domain.TrackedLink) ([]*application.ResourceShot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchResource", ctx, link)
	ret0, _ := ret[0].([]*application.ResourceShot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchResource indicates an expected call of SearchResource.
func (mr *MockSourceCrawlerMockRecorder) SearchResource(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchResource", reflect.TypeOf((*MockSourceCrawler)(nil).SearchResource), ctx, link)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// AddBatch mocks base method.
func (m *MockOutboxRepository) AddBatch(ctx context.Context, shot []*application.ResourceShot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBatch", ctx, shot)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBatch indicates an expected call of AddBatch.
func (mr *MockOutboxRepositoryMockRecorder) AddBatch(ctx, shot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBatch", reflect.TypeOf((*MockOutboxRepository)(nil).AddBatch), ctx, shot)
}
