// Code generated by MockGen. DO NOT EDIT.
// Source: command_service.go
//
// Generated by this command:
//
//	mockgen -source=command_service.go -exclude_interfaces=MetricsRecorder -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/n1jke/linktracker/internal/bot/application"
	domain "github.com/n1jke/linktracker/internal/scrapper/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatStateRepository is a mock of ChatStateRepository interface.
type MockChatStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatStateRepositoryMockRecorder
	isgomock struct{}
}

// MockChatStateRepositoryMockRecorder is the mock recorder for MockChatStateRepository.
type MockChatStateRepositoryMockRecorder struct {
	mock *MockChatStateRepository
}

// NewMockChatStateRepository creates a new mock instance.
func NewMockChatStateRepository(ctrl *gomock.Controller) *MockChatStateRepository {
	mock := &MockChatStateRepository{ctrl: ctrl}
	mock.recorder = &MockChatStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatStateRepository) EXPECT() *MockChatStateRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockChatStateRepository) Get(chatID int64) application.ChatState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", chatID)
	ret0, _ := ret[0].(application.ChatState)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockChatStateRepositoryMockRecorder) Get(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChatStateRepository)(nil).Get), chatID)
}

// Remove mocks base method.
func (m *MockChatStateRepository) Remove(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", chatID)
}

// Remove indicates an expected call of Remove.
func (mr *MockChatStateRepositoryMockRecorder) Remove(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockChatStateRepository)(nil).Remove), chatID)
}

// SetTags mocks base method.
func (m *MockChatStateRepository) SetTags(chatID int64, tags []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTags", chatID, tags)
}

// SetTags indicates an expected call of SetTags.
func (mr *MockChatStateRepositoryMockRecorder) SetTags(chatID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockChatStateRepository)(nil).SetTags), chatID, tags)
}

// SetURL mocks base method.
func (m *MockChatStateRepository) SetURL(chatID int64, url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetURL", chatID, url)
}

// SetURL indicates an expected call of SetURL.
func (mr *MockChatStateRepositoryMockRecorder) SetURL(chatID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetURL", reflect.TypeOf((*MockChatStateRepository)(nil).SetURL), chatID, url)
}

// StartTracking mocks base method.
func (m *MockChatStateRepository) StartTracking(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartTracking", chatID)
}

// StartTracking indicates an expected call of StartTracking.
func (mr *MockChatStateRepositoryMockRecorder) StartTracking(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTracking", reflect.TypeOf((*MockChatStateRepository)(nil).StartTracking), chatID)
}

// MockScrapper is a mock of Scrapper interface.
type MockScrapper struct {
	ctrl     *gomock.Controller
	recorder *MockScrapperMockRecorder
	isgomock struct{}
}

// MockScrapperMockRecorder is the mock recorder for MockScrapper.
type MockScrapperMockRecorder struct {
	mock *MockScrapper
}

// NewMockScrapper creates a new mock instance.
func NewMockScrapper(ctrl *gomock.Controller) *MockScrapper {
	mock := &MockScrapper{ctrl: ctrl}
	mock.recorder = &MockScrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapper) EXPECT() *MockScrapperMockRecorder {
	return m.recorder
}

// AddTags mocks base method.
func (m *MockScrapper) AddTags(ctx context.Context, chatID int64, link string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTags", ctx, chatID, link, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTags indicates an expected call of AddTags.
func (mr *MockScrapperMockRecorder) AddTags(ctx, chatID, link, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTags", reflect.TypeOf((*MockScrapper)(nil).AddTags), ctx, chatID, link, tags)
}

// ClearTags mocks base method.
func (m *MockScrapper) ClearTags(ctx context.Context, chatID int64, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTags", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTags indicates an expected call of ClearTags.
func (mr *MockScrapperMockRecorder) ClearTags(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTags", reflect.TypeOf((*MockScrapper)(nil).ClearTags), ctx, chatID, link)
}

// ListLinks mocks base method.
func (m *MockScrapper) ListLinks(ctx context.Context, chatID int64) ([]*domain.LinkSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinks", ctx, chatID)
	ret0, _ := ret[0].([]*domain.LinkSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinks indicates an expected call of ListLinks.
func (mr *MockScrapperMockRecorder) ListLinks(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinks", reflect.TypeOf((*MockScrapper)(nil).ListLinks), ctx, chatID)
}

// RegisterChat mocks base method.
func (m *MockScrapper) RegisterChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockScrapperMockRecorder) RegisterChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockScrapper)(nil).RegisterChat), ctx, chatID)
}

// TrackLink mocks base method.
func (m *MockScrapper) TrackLink(ctx context.Context, chatID int64, link string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackLink", ctx, chatID, link, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackLink indicates an expected call of TrackLink.
func (mr *MockScrapperMockRecorder) TrackLink(ctx, chatID, link, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackLink", reflect.TypeOf((*MockScrapper)(nil).TrackLink), ctx, chatID, link, tags)
}

// UntrackLink mocks base method.
func (m *MockScrapper) UntrackLink(ctx context.Context, chatID int64, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntrackLink", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// UntrackLink indicates an expected call of UntrackLink.
func (mr *MockScrapperMockRecorder) UntrackLink(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntrackLink", reflect.TypeOf((*MockScrapper)(nil).UntrackLink), ctx, chatID, link)
}
