apiVersion: 1
groups:
  - orgId: 1
    name: ram-alert
    folder: link-tracker
    interval: 30s
    rules:
      - uid: high_memory_usage
        title: High Memory Usage
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: process_resident_memory_bytes{job=~"bot|scrapper|agent"} > 200 * 1024 * 1024
              refId: A
        for: 1m
        noDataState: Alerting
        execErrState: Alerting
        labels:
          severity: "3"
        annotations:
          summary: "High memory on {{ $labels.job }}"
