// Code generated by MockGen. DO NOT EDIT.
// Source: process_case.go
//
// Generated by this command:
//
//	mockgen -source process_case.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/n1jke/linktracker_eng/internal/agent/application"
	domain "github.com/n1jke/linktracker_eng/internal/agent/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// AddBatch mocks base method.
func (m *MockOutboxRepository) AddBatch(ctx context.Context, updates []*application.ProcessedUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBatch", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBatch indicates an expected call of AddBatch.
func (mr *MockOutboxRepositoryMockRecorder) AddBatch(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBatch", reflect.TypeOf((*MockOutboxRepository)(nil).AddBatch), ctx, updates)
}

// MockSummarize is a mock of Summarize interface.
type MockSummarize struct {
	ctrl     *gomock.Controller
	recorder *MockSummarizeMockRecorder
	isgomock struct{}
}

// MockSummarizeMockRecorder is the mock recorder for MockSummarize.
type MockSummarizeMockRecorder struct {
	mock *MockSummarize
}

// NewMockSummarize creates a new mock instance.
func NewMockSummarize(ctrl *gomock.Controller) *MockSummarize {
	mock := &MockSummarize{ctrl: ctrl}
	mock.recorder = &MockSummarizeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummarize) EXPECT() *MockSummarizeMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockSummarize) Handle(ctx context.Context, d domain.Description) (domain.Description, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, d)
	ret0, _ := ret[0].(domain.Description)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockSummarizeMockRecorder) Handle(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockSummarize)(nil).Handle), ctx, d)
}
